# Generated by Django 5.2.13 on 2026-04-27 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('timeframe', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', 'Daily')], max_length=10)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol__ba87d3_idx')],
                'unique_together': {('symbol', 'timestamp', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('signal_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta'), ('BREAKOUT', 'Breakout'), ('REVERSAL', 'Reversión')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_level', models.DecimalField(decimal_places=5, max_digits=10)),
                ('timeframe', models.CharField(max_length=10)),
                ('indicators', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol__f94c9f_idx')],
            },
        ),
    ]
