# Generated by Django 4.2 on 2026-04-27 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketdata',
            name='market_data_symbol__ba87d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradingsignal',
            name='market_data_symbol__f94c9f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tradingsignal',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='tradingsignal',
            name='price_level',
        ),
        migrations.AddField(
            model_name='marketdata',
            name='bollinger_lower',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='bollinger_upper',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketdata',
            name='macd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='macd_histogram',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='macd_signal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='rsi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='breakout_level',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='volume_spike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='close_price',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='high_price',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='low_price',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='open_price',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='timeframe',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='signal_type',
            field=models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta'), ('BREAKOUT_UP', 'Ruptura Alcista'), ('BREAKOUT_DOWN', 'Ruptura Bajista'), ('CONSOLIDATION', 'Consolidación')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together={('symbol', 'timeframe', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='market_data_symbol__15958c_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='market_data_symbol__1ab00c_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['signal_type', 'active'], name='market_data_signal__390355_idx'),
        ),
    ]
