# Generated by Django 4.2 on 2026-04-27 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_remove_marketdata_market_data_symbol__ba87d3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='category',
            field=models.CharField(default='Forex', max_length=50),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
