# Generated by Django 4.2 on 2026-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_alter_marketdata_created_at_alter_symbol_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='signal_type',
            field=models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta'), ('BREAKOUT_UP', 'Ruptura Alcista'), ('BREAKOUT_DOWN', 'Ruptura Bajista'), ('CONSOLIDATION', 'Consolidación'), ('HOLD', 'Mantener')], max_length=20),
        ),
    ]
