# Generated by Django 4.2 on 2026-04-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_alter_tradingsignal_signal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado del Sistema',
                'verbose_name_plural': 'Estados del Sistema',
            },
        ),
    ]
