# Generated by Django 4.2 on 2026-04-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_systemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
