# Generated by Django 4.2 on 2026-04-27 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0003_alter_marketdata_created_at_alter_symbol_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('macd_histogram', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bollinger_upper', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bollinger_middle', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bollinger_lower', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('trend_direction', models.CharField(choices=[('UP', 'Alcista'), ('DOWN', 'Bajista'), ('SIDEWAYS', 'Lateral')], default='SIDEWAYS', max_length=10)),
                ('breakout_detected', models.BooleanField(default=False)),
                ('breakout_type', models.CharField(blank=True, choices=[('SUPPORT', 'Soporte'), ('RESISTANCE', 'Resistencia'), ('TRENDLINE', 'Línea de Tendencia'), ('CHANNEL', 'Canal')], max_length=20, null=True)),
                ('breakout_direction', models.CharField(blank=True, choices=[('UP', 'Ruptura Alcista'), ('DOWN', 'Ruptura Bajista')], max_length=10, null=True)),
                ('recommendation', models.CharField(choices=[('STRONG_BUY', 'Fuerte Compra'), ('BUY', 'Compra'), ('HOLD', 'Mantener'), ('SELL', 'Venta'), ('STRONG_SELL', 'Fuerte Venta')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='BreakoutAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=10)),
                ('analysis_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('breakout_type', models.CharField(choices=[('SUPPORT', 'Soporte'), ('RESISTANCE', 'Resistencia'), ('TRENDLINE', 'Línea de Tendencia'), ('CHANNEL', 'Canal')], max_length=20)),
                ('breakout_direction', models.CharField(choices=[('UP', 'Ruptura Alcista'), ('DOWN', 'Ruptura Bajista')], max_length=10)),
                ('breakout_level', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('volume_spike', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('confirmation_candles', models.IntegerField(default=0)),
                ('trading_signal', models.CharField(choices=[('BUY', 'Comprar'), ('SELL', 'Vender'), ('HOLD', 'Esperar'), ('NONE', 'Sin señal')], default='NONE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.symbol')),
            ],
        ),
        migrations.AddIndex(
            model_name='technicalanalysis',
            index=models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='analysis_te_symbol__32f615_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalanalysis',
            index=models.Index(fields=['breakout_detected', 'recommendation'], name='analysis_te_breakou_0524a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalanalysis',
            unique_together={('symbol', 'timeframe', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='breakoutanalysis',
            index=models.Index(fields=['symbol', 'timeframe', 'analysis_timestamp'], name='analysis_br_symbol__aaf2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='breakoutanalysis',
            index=models.Index(fields=['breakout_type', 'breakout_direction'], name='analysis_br_breakou_7295d1_idx'),
        ),
        migrations.AddIndex(
            model_name='breakoutanalysis',
            index=models.Index(fields=['is_valid', 'trading_signal'], name='analysis_br_is_vali_b18b42_idx'),
        ),
    ]
